project:
  orm:
    user: db_user
    password: *****
    db_name: blog
  files:
    static_dir: static
    upload_dir: static/upload
  timezone: UTC
  language: en
  homepage: blog.blog.index
  middlewares:
  - webpages.core.middleware.Cookie
  - webpages.core.middleware.Session
  - webpages.user.middleware.User

# blog app settings
blog:
  add_comments: no